version: "3.3"
services:
  api:
    user: ${UID}:${GID}
    image: flask_api_dev
    stdin_open: True
    container_name: ml_api_dev
    build:
      args:
        - UID=${UID}
        - GID=${GID}
        - PASSR=${PASSR}
        - PASSA=${PASSA}
      context: ./api
      target: dev
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - redis
      - model
    volumes:
      - ./api:/src
      - ./feedback:/src/feedback
      - ./uploads:/src/static/uploads

  redis:
    image: redis:6.2.6
    stdin_open: True
    container_name: redis_dev

  model:
    user: ${UID}:${GID}
    image: ml_service_dev
    stdin_open: True
    build:
      args:
        - UID=${UID}
        - GID=${GID}
        - PASSR=${PASSR}
        - PASSA=${PASSA}
      context: ./model
      target: dev
    depends_on:
      - redis
    volumes:
      - ./model:/src
      - ./uploads:/src/uploads
